micronaut:
  application:
    name: micronaut-users

datasources:
  default:
    url: jdbc:mysql://db:3306/app?autoReconnect=true&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: rootpasswd
